// Static build for Vercel (no dependencies): copies the site into dist/ and writes dist/js/config.js
// from environment variables. Run locally with:  SUPABASE_URL=... SUPABASE_ANON_KEY=... node scripts/build.js
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const dist = path.join(root, 'dist');
const SITE = ['index.html', 'css', 'js', 'sprites'];

fs.rmSync(dist, { recursive: true, force: true });
for (const entry of SITE) fs.cpSync(path.join(root, entry), path.join(dist, entry), { recursive: true });

// The Vercel ↔ Supabase integration sets SUPABASE_URL / SUPABASE_ANON_KEY (and NEXT_PUBLIC_* copies).
const env = process.env;
const url = env.SUPABASE_URL || env.NEXT_PUBLIC_SUPABASE_URL || '';
const key = env.SUPABASE_ANON_KEY || env.NEXT_PUBLIC_SUPABASE_ANON_KEY || env.SUPABASE_PUBLISHABLE_KEY || '';
if (key.startsWith('sb_secret_') || /service_role/.test(Buffer.from((key.split('.')[1] || ''), 'base64').toString())) {
  console.error('Refusing to build: SUPABASE_ANON_KEY is a secret (service_role) key. Use the anon / publishable key.');
  process.exit(1);
}
fs.writeFileSync(path.join(dist, 'js', 'config.js'),
  `/* Generated by scripts/build.js */\nwindow.SR_CONFIG = ${JSON.stringify({ supabaseUrl: url, supabaseAnonKey: key }, null, 2)};\n`);

// Cache-bust script and style URLs so a redeploy is picked up immediately.
const v = (env.VERCEL_GIT_COMMIT_SHA || Date.now().toString(36)).slice(0, 8);
const html = fs.readFileSync(path.join(dist, 'index.html'), 'utf8').replace(/(src="js\/[^"]+\.js|href="css\/[^"]+\.css)"/g, `$1?v=${v}"`);
fs.writeFileSync(path.join(dist, 'index.html'), html);

console.log(`Built dist/ (${url ? 'Supabase mode: ' + url : 'local demo mode: no SUPABASE_URL set'})`);
