// Writes supabase/seed.sql from js/data.js so the database catalog matches the site exactly.
// Usage: node scripts/make-seed.js   (re-run after changing prices or cases, then run seed.sql again)
const fs = require('fs');
const path = require('path');
const vm = require('vm');

const root = path.join(__dirname, '..');
const sandbox = { window: {} };
sandbox.SR = sandbox.window.SR = {};
vm.runInNewContext(fs.readFileSync(path.join(root, 'js', 'data.js'), 'utf8'), sandbox);
const { ITEMS, CASES } = sandbox.SR;

const q = v => (v === null || v === undefined ? 'null' : typeof v === 'number' ? String(v) : `'${String(v).replace(/'/g, "''")}'`);
const chunks = (arr, n) => { const out = []; for (let i = 0; i < arr.length; i += n) out.push(arr.slice(i, i + n)); return out; };

const items = Object.values(ITEMS);
let sql = `-- Generated by scripts/make-seed.js from js/data.js on ${new Date().toISOString().slice(0, 10)}. Safe to re-run.
begin;
`;
for (const part of chunks(items, 400)) {
  sql += `insert into public.items (id, weapon, finish, wear, type, tier, price, color, sheet, cell) values\n`
    + part.map(i => `(${[i.id, i.weapon, i.finish, i.wear, i.type, i.tier, i.price, i.color, i.sheet, i.cell].map(q).join(', ')})`).join(',\n')
    + `\non conflict (id) do update set weapon = excluded.weapon, finish = excluded.finish, wear = excluded.wear, type = excluded.type,
  tier = excluded.tier, price = excluded.price, color = excluded.color, sheet = excluded.sheet, cell = excluded.cell;\n`;
}
sql += `insert into public.cases (id, name, grp, glow, price, sort) values\n`
  + CASES.map((c, i) => `(${[c.id, c.name, c.group, c.glow, c.price, i].map(q).join(', ')})`).join(',\n')
  + `\non conflict (id) do update set name = excluded.name, grp = excluded.grp, glow = excluded.glow, price = excluded.price, sort = excluded.sort;\n`;
sql += `delete from public.case_items;\n`;
const rows = CASES.flatMap(c => c.contents.map((x, ord) => `(${[c.id, ord, x.id, x.chance].map(q).join(', ')})`));
for (const part of chunks(rows, 500)) sql += `insert into public.case_items (case_id, ord, item_id, chance) values\n${part.join(',\n')};\n`;
sql += `commit;\n`;

fs.mkdirSync(path.join(root, 'supabase'), { recursive: true });
fs.writeFileSync(path.join(root, 'supabase', 'seed.sql'), sql);
console.log(`supabase/seed.sql: ${items.length} items, ${CASES.length} cases, ${rows.length} case rows (${(sql.length / 1024).toFixed(0)} KB)`);
