// Writes supabase/seed.sql from js/data.js so the database catalog matches the site exactly.
// Usage: node scripts/make-seed.js   (re-run after changing prices or cases, then run seed.sql again)
// Items go in as one JSON row per skin; Postgres expands each skin's other wears into their own items.
const fs = require('fs');
const path = require('path');
const vm = require('vm');

const root = path.join(__dirname, '..');
const sandbox = { window: {} };
sandbox.SR = sandbox.window.SR = {};
vm.runInNewContext(fs.readFileSync(path.join(root, 'js', 'data.js'), 'utf8'), sandbox);
const { ITEMS, CASES } = sandbox.SR;

const q = v => (v === null || v === undefined ? 'null' : typeof v === 'number' ? String(v) : `'${String(v).replace(/'/g, "''")}'`);
const chunks = (arr, n) => { const out = []; for (let i = 0; i < arr.length; i += n) out.push(arr.slice(i, i + n)); return out; };

const all = Object.values(ITEMS);
const skins = all.filter(i => i.main).map(i => ({
  i: i.id, w: i.weapon, f: i.finish, wr: i.wear, t: i.type, r: i.tier, p: i.price, c: i.color, s: i.sheet, k: i.cell,
  o: all.filter(v => !v.main && v.base === i.id).map(v => [v.wear, v.price]),
}));
const json = JSON.stringify(skins);
if (json.includes('$skins$')) throw new Error('dollar-quote tag collides with data');

let sql = `-- Generated by scripts/make-seed.js from js/data.js on ${new Date().toISOString().slice(0, 10)}. Safe to re-run.
-- Needs supabase/migrations/0003_upgrades_and_wears.sql first (items.base / items.main columns).
begin;

create temporary table _skins on commit drop as
select * from jsonb_to_recordset($skins$${json}$skins$::jsonb)
  as x(i text, w text, f text, wr text, t text, r text, p numeric, c text, s int, k int, o jsonb);

insert into public.items (id, weapon, finish, wear, type, tier, price, color, sheet, cell, base, main)
select i, w, f, wr, t, r, p, c, s, k, i, true from _skins
union all
select i || '-' || lower(v ->> 0), w, f, v ->> 0, t, r, (v ->> 1)::numeric, c, s, k, i, false
from _skins, jsonb_array_elements(o) v
on conflict (id) do update set weapon = excluded.weapon, finish = excluded.finish, wear = excluded.wear, type = excluded.type,
  tier = excluded.tier, price = excluded.price, color = excluded.color, sheet = excluded.sheet, cell = excluded.cell,
  base = excluded.base, main = excluded.main;

`;
sql += `insert into public.cases (id, name, grp, glow, price, sort) values\n`
  + CASES.map((c, i) => `(${[c.id, c.name, c.group, c.glow, c.price, i].map(q).join(', ')})`).join(',\n')
  + `\non conflict (id) do update set name = excluded.name, grp = excluded.grp, glow = excluded.glow, price = excluded.price, sort = excluded.sort;\n\n`;
sql += `delete from public.case_items;\n`;
const rows = CASES.flatMap(c => c.contents.map((x, ord) => `(${[c.id, ord, x.id, x.chance].map(q).join(', ')})`));
for (const part of chunks(rows, 500)) sql += `insert into public.case_items (case_id, ord, item_id, chance) values\n${part.join(',\n')};\n`;
sql += `commit;\n`;

fs.mkdirSync(path.join(root, 'supabase'), { recursive: true });
fs.writeFileSync(path.join(root, 'supabase', 'seed.sql'), sql);
console.log(`supabase/seed.sql: ${skins.length} skins → ${all.length} items, ${CASES.length} cases, ${rows.length} case rows (${(sql.length / 1024).toFixed(0)} KB)`);
